language: php
dist: trusty

php:
  - nightly
  - 7.3
  - 7.2
  - 7.1
  - 7.0

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

notifications:
  email: false
